name: CI

on:
  push:
    branches: [ main ]

jobs:
  integrationTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm start &
      - run: npx newman run ./tests/api.json --env-var "baseUrl=http://localhost:8080"
      